# Generated by Django 3.1.4 on 2021-07-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210721_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='timestamp',
        ),
    ]
