# Generated by Django 3.1.4 on 2021-07-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogcomment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
