# Generated by Django 3.1.4 on 2021-07-21 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogcomment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
